version: '3.4'


services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile    
  postgres:
    image: postgres
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  redis:
    image: redis
    container_name: my_redis_container
    ports:
      - "6379:6379"
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge








